[package]
name = "perp-deploy-set-oracle"
version = "0.1.0"
edition = "2024"

[dependencies]
hl-rs = { path = "../../" }

alloy = "1.1.1"
dotenv = "0.15.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros"] }
